name: CI Checks

on:
  pull_request:
    # types:
    #   - opened
    #   - synchronize
    #   - reopened
    #   # When a PR is closed, we still start this workflow, but then skip
    #   # all the jobs, which makes it effectively a no-op.  The reason to
    #   # do this is that it allows us to take advantage of concurrency groups
    #   # to cancel in progress CI jobs whenever the PR is closed.
    #   - closed
  workflow_dispatch:
  push:
    # branches:
    #   - 'release/**'

env:
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup VS environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Tell sccache to use Actions cache
        run: Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_GHA_ENABLED=true"

      - name: Configure
        run: |
          cmake -G Ninja -B build -S llvm ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DLLVM_ENABLE_PROJECTS=clang ^
            -DCMAKE_C_COMPILER_LAUNCHER=sccache ^
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
        shell: cmd

      - name: Build all
        run: ninja -C build

      - name: Test with llvm-lit
        continue-on-error: true
        run: |
          ./build/bin/llvm-lit -v clang/test/Driver/fsanitize-compilation-dir.c
          ./build/bin/llvm-lit -v clang/test/CodeGen/ubsan-sanitize-compilation-dir.cpp
          ./build/bin/llvm-lit -v clang/test/CodeGen/asan-sanitize-compilation-dir.c

      - name: Build
        run: ninja -C build check-clang-driver check-clang-codegen

