name: CI Checks

on:
  pull_request:
    # types:
    #   - opened
    #   - synchronize
    #   - reopened
    #   # When a PR is closed, we still start this workflow, but then skip
    #   # all the jobs, which makes it effectively a no-op.  The reason to
    #   # do this is that it allows us to take advantage of concurrency groups
    #   # to cancel in progress CI jobs whenever the PR is closed.
    #   - closed
  workflow_dispatch:
  push:
    # branches:
    #   - 'release/**'

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup VS environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        run: choco install ninja

      - name: Configure
        run: |
          cmake -G Ninja -B build -S llvm ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DLLVM_ENABLE_PROJECTS="clang" ^
            -DLLVM_ENABLE_ASSERTIONS=ON
        shell: cmd

      - name: Build
        run: ninja -C build

      - name: Test
        run: ninja -C build check-clang
